---
functional:
  - Наличие возможности регистрации пользователей и их последующей авторизации
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Наличие полей для ввода персональных данных пользователя (фамилии, имени, номера телефона и почты)
  - Наличие контроля за заполнением полей и предупреждение о неправильном вводе (невводе) данных
  - Наличие обратной связи, возможности связаться с менеджером или администратором
  - Возможность переключения языков 
